### ISSUE TITLE
Squad Vingadores

### ISSUE THREAD

**Issue by matheusPierro** [mvalbuquerque/squad#3]
https://github.com/fehstack/Vingadores

**Comment by mvalbuquerque** [comment]
Olá! @matheusPierro faltou o nome dos integrantes da sua squad. Aguardo. Profº Vinny

**Comment by matheusPierro** [comment]
Claro! Segue abaixo os integrantes da nossa squad:
Matheus Ramos de Pierro
Thiago Gyorgy
Felipe Santiago
Gabriel Tricerri

**Comment by mvalbuquerque** [comment]
Ótimo ! Obrigado pelo envio. Abs
